### ISSUE TITLE
Tagged release source tarball for the bioconda recipe linter please?

### ISSUE THREAD

**Issue by fubar2** [marbl/seqrequester#10]
Hello @brianwalenz and @arangrhie !

After a talk Arang gave to the VGP Galaxy group, they would like to use this package for workflows, but that means creating a Conda recipe to use in a new tool.

I have some good news: I've [got a conda recipe working](https://github.com/fubar2/bioconda-recipes/tree/seqrequester/recipes/seqrequester) for seqrequester - using `git-url` as the source. Bioconda is the right place for this package but the bad news is that lint fails. For reproducibility, Bioconda insists on a stable long term archive URI and won't even allow a specific revision git clone. 

At present, the github tags [zip/tgz](https://github.com/marbl/seqrequester/archive/refs/tags/v0.0.zip) link to empty files - if you could please make a github release, I can fix the recipe to download it from a stable URI and get your package into Bioconda if that is ok?

Thanks!

**Comment by brianwalenz** [comment]
Hi Ross-  Hopefully I got all the correct boxes checked and i's properly dotted.

Release is tagged as 'v1.0' with a maintenance branch 'v1.0-maintenance'.  Release itself is at https://github.com/marbl/seqrequester/releases/tag/v1.0

**Comment by fubar2** [comment]
Hi @brianwalenz: Thank you!
 
Will let you know how it goes using the URI https://github.com/marbl/seqrequester/archive/refs/tags/v1.0.tar.gz

**Comment by fubar2** [comment]
Hi @brianwalenz,

Bioconda lint is now satisfied with the URI, but of course it's never that simple....

Currently a git clone will compile, but neither that new release tarball nor the code download zip will compile, so bioconda build for the release tarball fails. 

```
Fetching submodule 'utility'
 - fatal: not a git repository (or any of the parent directories): .git
make: ./utility/src/version.pl: No such file or directory
Makefile:444: *** Failed to create version.H, possibly missing the 'meryl-utility' submodule.  Stop.
```

Fix is to add the missing .git directory to the release I think - at least it compiles normally if I add a copy here.

**Comment by fubar2** [comment]
Closing this. Can reopen if anyone cares and can make a working release URI.
