### ISSUE TITLE
some errors for Makefile

### ISSUE THREAD

**Issue by cao-ben** [marbl/seqrequester#6]
I observe that the Makefile file was recently updated, but I encountered an error with no rules to make the target, causing the make execution to stop.

There are no rules for making the target “share/seqrequester/ultra-long-nanopore”，由“/home/bio-3090ti/Benz_code/GNNome-assembly/vendor/seqrequester/build/share/seqrequester/ultra-long-nanopore” requirements. Stop.

**Comment by brianwalenz** [comment]
A fresh clone built fine for me with GNU Make 4.3.  Which version are you using?

The source of the file it is trying to install is `..../vendor/seqrequester/share/ultra-long-nanopore`; does that file exist?

The error message is unfamiliar.  If I remove that file and try building, I get:
```
gmake: *** No rule to make target '../share/ultra-long-nanopore', needed by '/scratch/seqrequester/build/share/seqrequester/ultra-long-nanopore'.  Stop.
```
which is worded differently, but more importantly, the target path is quite different.

**Comment by cao-ben** [comment]
> A fresh clone built fine for me with GNU Make 4.3. Which version are you using?
> 
> The source of the file it is trying to install is `..../vendor/seqrequester/share/ultra-long-nanopore`; does that file exist?
> 
> The error message is unfamiliar. If I remove that file and try building, I get:
> 
> ```
> gmake: *** No rule to make target '../share/ultra-long-nanopore', needed by '/scratch/seqrequester/build/share/seqrequester/ultra-long-nanopore'.  Stop.
> ```
> 
> which is worded differently, but more importantly, the target path is quite different.
Thank you for your reply. I used GNU Make 4.2.1. Should i update my Make?  And Yes, **_ultra-long-nanopore_** is already exists, should I remove it and reinstall it, or has it been stated that I have installed successfully.    Beside. I found it under the path "../seqrequester/build/bin/seqrequester", Is this proof that I finished the **_seqrequester_** installation? Thanks again

**Comment by cao-ben** [comment]
And I've noticed there seems to be a difference in our paths 
 `share/seqrequester/ultra-long-nanopore` its me
`seqrequester/share/ultra-long-nanopore` its your
Is it because the path is reversed that **_ultra-long-nanopore_** can't find it？But I didn't change the Makefile.
if yes, Although this sounds simple, I am not familiar with the syntax of cmake. So I need you to help me check, thank you !~

**Comment by brianwalenz** [comment]
I'm not sure what's going wrong here.  If you have these four files, it installed correctly:
```
> ls -l build/share/seqrequester/* build/bin/seqrequester 
-rwxr-xr-x  1 bri  bri  2417928 Jun 24 10:48 build/bin/seqrequester
-rw-r--r--  1 bri  bri  1139703 Jun 24 09:31 build/share/seqrequester/pacbio
-rw-r--r--  1 bri  bri    97398 Jun 24 09:31 build/share/seqrequester/pacbio-hifi
-rw-r--r--  1 bri  bri  2040814 Jun 24 09:31 build/share/seqrequester/ultra-long-nanopore
```
(The size of 'seqrequester' will be different.)  I suspect you're missing the last three, but you can install manually:
```
cp share/* build/share/seqrequester/
```

**Comment by cao-ben** [comment]
u are right. I have this file `build/bin/seqrequester`, but dont have others. So i used u solution. `cp share/* build/share/seqrequester/`, and i find other 3 file in same path sa u. So I guess I'm done with the installation. Since I didn't download the dataset I just run `/seqrequester/build/bin/seqrequester`, I received the following output:


```
usage: /home/bio-3090ti/Benz_code/GNNome-assembly/vendor/seqrequester/build/bin/seqrequester [mode] [options] [sequence_file ...]

MODES:
  summarize      report N50, length histogram, mono-, di- and tri-nucleotide frequencies
  extract        extract the specified sequences
  sample         emit existing sequences randomly
  generate       generate random sequences
  microsatellite compute microsatellite percent per window size
  simulate       errors in existing sequences

ERROR:  No mode (summarize, extract, generate, et cetera) specified.
ERROR:  Supplied options don't make sense.
```

I think I'm done with the installation. Thank u very much~I'll run it on the instance as much as possible

**Comment by brianwalenz** [comment]
I finally figured out this problem.  Cheers!
